/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PrawnSeed } from "./PrawnSeed";
import { PrawnSeedCountArgs } from "./PrawnSeedCountArgs";
import { PrawnSeedFindManyArgs } from "./PrawnSeedFindManyArgs";
import { PrawnSeedFindUniqueArgs } from "./PrawnSeedFindUniqueArgs";
import { DeletePrawnSeedArgs } from "./DeletePrawnSeedArgs";
import { PrawnSeedService } from "../prawnSeed.service";
@graphql.Resolver(() => PrawnSeed)
export class PrawnSeedResolverBase {
  constructor(protected readonly service: PrawnSeedService) {}

  async _prawnSeedsMeta(
    @graphql.Args() args: PrawnSeedCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PrawnSeed])
  async prawnSeeds(
    @graphql.Args() args: PrawnSeedFindManyArgs
  ): Promise<PrawnSeed[]> {
    return this.service.prawnSeeds(args);
  }

  @graphql.Query(() => PrawnSeed, { nullable: true })
  async prawnSeed(
    @graphql.Args() args: PrawnSeedFindUniqueArgs
  ): Promise<PrawnSeed | null> {
    const result = await this.service.prawnSeed(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PrawnSeed)
  async deletePrawnSeed(
    @graphql.Args() args: DeletePrawnSeedArgs
  ): Promise<PrawnSeed | null> {
    try {
      return await this.service.deletePrawnSeed(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
